name: Reusable Veracode Scan for .NET Framework

on:
  workflow_call:
    inputs:
      sln_file:
        required: true
        type: string
      project_path:
        required: true
        type: string
    secrets:
      VERACODE_API_ID:
        required: true
      VERACODE_API_KEY:
        required: true

jobs:
  veracode-scan:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet Packages
        run: nuget restore ${{ inputs.sln_file }}

      - name: Build Solution with MSBuild
        shell: powershell
        run: |
          $msbuild = (Get-ChildItem "C:\Program Files\Microsoft Visual Studio\2022" -Recurse -Filter MSBuild.exe | Select-Object -First 1).FullName
          Write-Host "Using MSBuild at: $msbuild"
          & $msbuild ${{ inputs.sln_file }} /p:Configuration=Release /p:Platform="Any CPU"

      # - name: Setup Java
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: 'temurin'
      #     java-version: '11'
      #     cache: 'maven'

      - name: Create artifact zip
        shell: powershell
        run: |
          Compress-Archive -Path "**/bin/Release/*" -DestinationPath veracode_artifact.zip -Force

      - name: Veracode Upload & Scan
        uses: veracode/veracode-uploadandscan-action@0.2.10
        with:
          appname: ${{ github.event.repository.name }}
          createprofile: true
          filepath: "veracode_artifact.zip"
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          scantimeout: 120
